import { Effect, Data } from "effect"
import { FileSystem } from "@effect/platform"
import matter from "gray-matter"

export class ManifestError extends Data.TaggedError("ManifestError")<{
  readonly message: string
  readonly cause?: unknown
}> {}

interface TopicEntry {
  slug: string
  title: string
  description: string
  order: number
  category: string
  tags: string[]
  relatedFiles: string[]
  content: string
}

export class ManifestGenerator extends Effect.Service<ManifestGenerator>()(
  "ManifestGenerator",
  {
    accessors: true,
    effect: Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem

      const generate = (topicsDir: string, outputFile: string) =>
        Effect.gen(function* () {
          const exists = yield* fs.exists(topicsDir)
          if (!exists) {
            return yield* Effect.fail(
              new ManifestError({ message: `Topics directory not found: ${topicsDir}` }),
            )
          }

          const files = yield* fs.readDirectory(topicsDir)
          const mdFiles = files.filter((f) => f.endsWith(".md")).sort()

          const topics: TopicEntry[] = []
          for (const file of mdFiles) {
            const raw = yield* fs.readFileString(`${topicsDir}/${file}`)
            const { data, content } = matter(raw)
            topics.push({
              slug: (data.slug as string) ?? file.replace(/\.md$/, "").replace(/^\d+-/, ""),
              title: (data.title as string) ?? file.replace(/\.md$/, ""),
              description: (data.description as string) ?? "",
              order: (data.order as number) ?? 0,
              category: (data.category as string) ?? "general",
              tags: (data.tags as string[]) ?? [],
              relatedFiles: (data.relatedFiles as string[]) ?? [],
              content: content.trim(),
            })
          }

          const output = `// Auto-generated by generate-manifest.ts — do not edit
export interface Topic {
  readonly slug: string
  readonly title: string
  readonly description: string
  readonly order: number
  readonly category: string
  readonly tags: readonly string[]
  readonly relatedFiles: readonly string[]
  readonly content: string
}

export const topics: readonly Topic[] = ${JSON.stringify(topics, null, 2)} as const
`
          const dir = outputFile.split("/").slice(0, -1).join("/")
          yield* fs.makeDirectory(dir, { recursive: true })
          yield* fs.writeFileString(outputFile, output)

          return topics.length
        }).pipe(
          Effect.mapError(
            (cause) => new ManifestError({ message: "Failed to generate manifest", cause }),
          ),
        )

      return { generate }
    }),
  },
) {}
