import type { ProjectConfig } from "../schemas/project-config.js"

export const docsManifestTs = (config: ProjectConfig): string =>
  `// Auto-generated by generate-manifest.ts — do not edit
export interface Topic {
  readonly slug: string
  readonly title: string
  readonly description: string
  readonly order: number
  readonly category: string
  readonly tags: readonly string[]
  readonly relatedFiles: readonly string[]
  readonly content: string
}

export const topics: readonly Topic[] = [
  {
    "slug": "overview",
    "title": "Overview",
    "description": "High-level overview of ${config.name}",
    "order": 0,
    "category": "general",
    "tags": ["overview", "getting-started"],
    "relatedFiles": [],
    "content": "# ${config.name} Overview\\n\\nWelcome to the ${config.name} solutions guide. This CLI provides curated documentation\\nto help you (and AI agents) navigate the ${config.name} codebase efficiently.\\n\\n## Getting Started\\n\\n- Run \`${config.cliName} list\` to see all available topics\\n- Run \`${config.cliName} show <topic>\` to read a specific topic\\n- Run \`${config.cliName} setup\` to initialize the reference\\n\\n## Topics\\n\\nTopics are organized by category and cover the key concepts, patterns, and\\narchitecture of this project. Each topic includes descriptions, code examples,\\nand pointers to relevant source files.\\n\\n## Adding Topics\\n\\nAdd new topics by creating markdown files in the \`${config.topicsDir}/\` directory\\nwith YAML frontmatter, then run \`bun run generate-manifest\` to rebuild."
  }
] as const
`
