import type { ProjectConfig } from "../schemas/project-config.js"

export const generateManifestTs = (config: ProjectConfig): string =>
  `import { readdir, readFile, writeFile } from "node:fs/promises"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import matter from "gray-matter"

const __dirname = dirname(fileURLToPath(import.meta.url))

interface TopicEntry {
  slug: string
  title: string
  description: string
  order: number
  category: string
  tags: string[]
  relatedFiles: string[]
  content: string
}

const topicsDir = join(__dirname, "..", "${config.topicsDir}")
const outputFile = join(__dirname, "..", "src", "docs-manifest.ts")

const files = (await readdir(topicsDir)).filter((f) => f.endsWith(".md")).sort()

const topics: TopicEntry[] = []
for (const file of files) {
  const raw = await readFile(join(topicsDir, file), "utf-8")
  const { data, content } = matter(raw)
  topics.push({
    slug: data.slug ?? file.replace(/\\.md$/, "").replace(/^\\d+-/, ""),
    title: data.title ?? file.replace(/\\.md$/, ""),
    description: data.description ?? "",
    order: data.order ?? 0,
    category: data.category ?? "general",
    tags: data.tags ?? [],
    relatedFiles: data.relatedFiles ?? [],
    content: content.trim(),
  })
}

const output = \`// Auto-generated by generate-manifest.ts — do not edit
export interface Topic {
  readonly slug: string
  readonly title: string
  readonly description: string
  readonly order: number
  readonly category: string
  readonly tags: readonly string[]
  readonly relatedFiles: readonly string[]
  readonly content: string
}

export const topics: readonly Topic[] = \${JSON.stringify(topics, null, 2)} as const
\`

await writeFile(outputFile, output, "utf-8")
console.log(\`Generated docs-manifest.ts with \${topics.length} topics\`)
`
